"""
Generate known-cards.yml from wiki card product articles.

The wiki articles in wiki/card-ops/cards/*.md are the source of truth.
Their YAML frontmatter contains machine-readable card data (earn_rates,
annual_fee, aliases, rate_overrides). This script reads all card articles,
extracts the structured data, and writes data/known-cards.yml.

Run this whenever a wiki article is created or updated.
"""
from __future__ import annotations

from pathlib import Path

import yaml


###############################################################################
# Paths
###############################################################################

REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
WIKI_CARDS_DIR = REPO_ROOT / "wiki" / "card-ops" / "cards"
KNOWN_CARDS_PATH = Path(__file__).resolve().parent.parent / "data" / "known-cards.yml"

# Fields to extract from frontmatter into known-cards.yml
_CARD_FIELDS = [
    "issuer",
    "card",
    "aliases",
    "annual_fee",
    "earn_rates",
    "rate_overrides",
    "notes",
    "requires",
]


###############################################################################
# Generator
###############################################################################

def _parse_frontmatter(filepath: Path) -> dict | None:
    """Extract YAML frontmatter from a markdown file.

    Returns the parsed dict, or None if no frontmatter found or if
    the file is not a card-product article.
    """
    text = filepath.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None

    # Find closing --- on its own line (not inside a comment)
    lines = text.split("\n")
    end_line = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end_line = i
            break

    if end_line is None:
        return None

    raw = "\n".join(lines[1:end_line])
    data = yaml.safe_load(raw)

    if not isinstance(data, dict):
        return None
    if data.get("type") != "card-product":
        return None
    if "slug" not in data or "earn_rates" not in data:
        return None

    return data


def generate() -> dict[str, dict]:
    """Read all wiki card articles and return a dict suitable for known-cards.yml."""
    cards: dict[str, dict] = {}

    for md_file in sorted(WIKI_CARDS_DIR.glob("*.md")):
        if md_file.name.startswith("_"):
            continue

        data = _parse_frontmatter(md_file)
        if data is None:
            continue

        slug = data["slug"]
        entry: dict = {}
        for field in _CARD_FIELDS:
            if field in data and data[field]:
                entry[field] = data[field]

        cards[slug] = entry

    return cards


def write_known_cards(cards: dict[str, dict] | None = None) -> Path:
    """Generate known-cards.yml from wiki articles.

    Returns the path to the written file.
    """
    if cards is None:
        cards = generate()

    from datetime import datetime, timezone

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    header = (
        "# Known Card Products -- GENERATED from wiki/card-ops/cards/*.md\n"
        "#\n"
        f"# Generated: {now}\n"
        f"# Cards: {len(cards)}\n"
        "#\n"
        "# DO NOT EDIT THIS FILE DIRECTLY.\n"
        "# Edit the wiki article, then run: python lib/generate_known_cards.py\n"
        "# Without wiki: use lib/card_lookup.py::add_card() to append directly.\n"
        "#\n"
        "# Fields:\n"
        "#   earn_rates: rate_key -> decimal rate (0.06 = 6%)\n"
        "#   annual_fee: integer dollars\n"
        "#   rate_overrides: merchant -> rate (issuer-specific exclusions)\n"
        "#   aliases: common names for lookup\n"
        "#   requires: conditions for stated rates\n"
        "\n"
    )

    yaml_body = yaml.dump(
        cards,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )

    KNOWN_CARDS_PATH.write_text(header + yaml_body, encoding="utf-8")
    return KNOWN_CARDS_PATH


###############################################################################
# CLI
###############################################################################

if __name__ == "__main__":
    cards = generate()
    path = write_known_cards(cards)
    print(f"Generated {path} with {len(cards)} cards:")
    for slug in cards:
        print(f"  {slug}")
